<?php
require_once ABSPATH . 'wp-admin/includes/template.php';
$billing_admin = get_user_by( 'login', 'reviewer' )->ID;
$payer = new_user( 'payer' ); $other_payer = new_user( 'other_payer' );
call_api( $payer, 'POST', 'entries', viewing( 'My retained paid diary' ) );
check( ! RT_Membership::enabled() && call_api( $payer, 'GET', 'entries' )->get_status() === 200, 'Billing remains disabled until the owner opens subscriptions' );
check( call_api( 0, 'POST', 'billing/checkout', array() )->get_status() === 401, 'Checkout requires a signed-in account' );
check( call_api( $payer, 'POST', 'billing/checkout', array( 'mode' => 'test' ) )->get_status() === 403, 'Ordinary users cannot start test-mode billing' );
check( call_api( $payer, 'GET', 'membership' )->get_data()['state'] === 'disabled', 'Users can inspect membership separately from diary access' );
wp_set_current_user( $payer );
check( is_wp_error( RT_Stripe_Settings::connect( 'test', 'sk_test_1234567890123456' ) ), 'Subscribers cannot configure Stripe credentials' );
wp_set_current_user( $billing_admin );
check( is_wp_error( RT_Stripe_Settings::connect( 'test', 'sk_live_1234567890123456' ) ), 'Setup rejects a key for the wrong billing mode' );
check( RT_Stripe_Settings::connect( 'test', 'sk_test_1234567890123456' ) === true && RT_Stripe::ready( 'test' ), 'Test setup prepares the recurring price, portal and webhook without charging anyone' );
$setup_calls = get_option( 'rt_mock_stripe_calls' );
$price_call = array_values( array_filter( $setup_calls, function ( $call ) { return 'prices' === $call['path']; } ) )[0];
check( $price_call['data']['unit_amount'] === '100' && $price_call['data']['currency'] === 'eur' && $price_call['data']['recurring']['interval'] === 'month' && $price_call['data']['tax_behavior'] === 'inclusive', 'The plan is exactly €1 per month with inclusive tax behavior' );
$portal_call = array_values( array_filter( $setup_calls, function ( $call ) { return 'billing_portal/configurations' === $call['path']; } ) )[0];
check( $portal_call['data']['features']['subscription_cancel']['mode'] === 'at_period_end', 'The customer portal supports cancellation at the end of the paid period' );
$hook_call = array_values( array_filter( $setup_calls, function ( $call ) { return 'webhook_endpoints' === $call['path']; } ) )[0];
check( $hook_call['data']['api_version'] === RT_Stripe::API_VERSION && count( $hook_call['data']['enabled_events'] ) === 6, 'Stripe uses a pinned API version and the required payment lifecycle events' );
$before_setup = count( get_option( 'rt_mock_stripe_calls' ) );
RT_Stripe_Settings::connect( 'test', '' );
check( count( get_option( 'rt_mock_stripe_calls' ) ) === $before_setup + 2, 'Reconnecting reuses the existing product, price, portal and webhook' );
update_option( 'rt_mock_charges_disabled', true );
check( is_wp_error( RT_Stripe_Settings::connect( 'live', 'sk_live_1234567890123456' ) ), 'Live setup requires a Stripe account enabled for charges' );
delete_option( 'rt_mock_charges_disabled' );
check( RT_Stripe_Settings::connect( 'live', 'sk_live_1234567890123456' ) === true, 'Live mode has a separate connection and price' );
check( is_wp_error( RT_Stripe_Settings::set_enabled( true ) ) && ! RT_Membership::enabled(), 'Paid access cannot open before a successful test payment and webhook' );

$test_checkout = call_api( $billing_admin, 'POST', 'billing/checkout', array( 'mode' => 'test' ) );
check( $test_checkout->get_status() === 200 && str_starts_with( $test_checkout->get_data()['url'], 'https://checkout.stripe.com/' ), 'An administrator can exercise test checkout before opening live billing' );
$test_session = rt_mock_complete_checkout( $billing_admin, 'test' );
check( RT_Stripe::reconcile_return( $billing_admin, 'test', $test_session ) === true, 'A checkout return verifies payment with Stripe before recording test success' );
check( is_wp_error( RT_Stripe_Settings::set_enabled( true ) ), 'A success redirect alone does not prove webhook delivery' );

function billing_event( $uid, $mode = 'live', $type = 'customer.subscription.updated', $changes = array(), $signed = true, $when = null ) {
    $row = RT_Stripe::row( $uid, $mode );
    $event = array_replace_recursive( array( 'id' => 'evt_fixture', 'livemode' => 'live' === $mode, 'type' => $type, 'data' => array( 'object' => array( 'customer' => $row['customer_id'] ) ) ), $changes );
    $body = wp_json_encode( $event ); $when = $when ?? time();
    wp_set_current_user( 0 );
    $request = new WP_REST_Request( 'POST', '/reel-together/v1/billing/webhook/' . $mode );
    $request->set_header( 'Content-Type', 'application/json' ); $request->set_body( $body );
    if ( $signed ) { $request->set_header( 'Stripe-Signature', 't=' . $when . ',v1=' . hash_hmac( 'sha256', $when . '.' . $body, RT_Stripe::config( $mode )['webhook_secret'] ) ); }
    return rest_do_request( $request );
}
check( billing_event( $billing_admin, 'test' )->get_status() === 200, 'A signed test event verifies webhook delivery' );
wp_set_current_user( $billing_admin );
update_option( 'rt_stripe_test_passed', 'acct_AnotherSandbox', false );
check( is_wp_error( RT_Stripe_Settings::set_enabled( true ) ), 'Test proof from a different sandbox cannot open paid access' );
update_option( 'rt_stripe_test_passed', RT_Stripe::config( 'test' )['account'], false );
check( RT_Stripe::config( 'test' )['account'] !== RT_Stripe::config( 'live' )['account'] && RT_Stripe_Settings::set_enabled( true ) === true && RT_Membership::enabled(), 'The owner can open billing after testing checkout and webhooks in a separate sandbox' );
check( call_api( $payer, 'GET', 'bootstrap' )->get_status() === 402 && call_api( $payer, 'POST', 'entries', viewing( 'Unpaid write' ) )->get_status() === 402, 'An unpaid Subscriber role cannot read or write diary data' );
check( call_api( $payer, 'GET', 'membership' )->get_status() === 200 && call_api( $payer, 'GET', 'membership' )->get_data()['state'] === 'inactive', 'An unpaid person can still open their billing status' );
check( call_api( $billing_admin, 'GET', 'bootstrap' )->get_status() === 200, 'Administrators retain access to manage the site' );
wp_set_current_user( $payer ); $_POST = array( 'rt_complimentary_access' => 'yes', 'rt_membership_access_nonce' => wp_create_nonce( 'rt_membership_access_' . $payer ) );
RT_Membership::save_user_profile( $payer );
check( ! get_user_meta( $payer, '_rt_complimentary_access', true ), 'Users cannot grant themselves complimentary access' );
wp_set_current_user( $billing_admin ); $_POST['rt_membership_access_nonce'] = 'invalid'; RT_Membership::save_user_profile( $payer );
check( ! get_user_meta( $payer, '_rt_complimentary_access', true ), 'Complimentary changes reject invalid nonces' );
$_POST['rt_membership_access_nonce'] = wp_create_nonce( 'rt_membership_access_' . $payer ); RT_Membership::save_user_profile( $payer ); $_POST = array();
check( call_api( $payer, 'GET', 'bootstrap' )->get_status() === 200 && RT_Membership::status()['state'] === 'complimentary', 'The owner can manually give a selected person free access' );
check( call_api( $payer, 'POST', 'billing/checkout', array() )->get_status() === 409, 'Complimentary users are not invited to buy an unnecessary subscription' );
wp_set_current_user( $billing_admin ); $_POST = array( 'rt_membership_access_nonce' => wp_create_nonce( 'rt_membership_access_' . $payer ) ); RT_Membership::save_user_profile( $payer ); $_POST = array();
check( call_api( $payer, 'GET', 'entries' )->get_status() === 402, 'Removing complimentary access requires that person to subscribe' );

$checkout = call_api( $payer, 'POST', 'billing/checkout', array( 'user_id' => $other_payer, 'price' => 'price_Fake', 'quantity' => 10, 'return_url' => 'https://evil.example' ) );
check( $checkout->get_status() === 200, 'A paying person can start Stripe Checkout' );
$row = RT_Stripe::row( $payer, 'live' );
$wpdb->update( RT_Store::table( 'billing_accounts' ), array( 'lock_until' => time() + 300 ), array( 'user_id' => $payer, 'mode' => 'live' ) );
check( call_api( $payer, 'POST', 'billing/checkout', array() )->get_status() === 409, 'Concurrent checkout preparation is serialized per account' );
$wpdb->update( RT_Store::table( 'billing_accounts' ), array( 'lock_until' => 0 ), array( 'user_id' => $payer, 'mode' => 'live' ) );
$calls = get_option( 'rt_mock_stripe_calls' ); $checkout_calls = array_values( array_filter( $calls, function ( $call ) { return $call['path'] === 'checkout/sessions' && $call['mode'] === 'live'; } ) );
$params = end( $checkout_calls )['data'];
check( $params['client_reference_id'] === (string) $payer && $params['line_items'][0]['quantity'] === '1' && $params['line_items'][0]['price'] === RT_Stripe::config( 'live' )['price'] && ! str_contains( $params['success_url'], 'evil.example' ), 'Checkout ignores client-supplied identity, price, quantity and redirect destinations' );
check( call_api( $payer, 'POST', 'billing/checkout', array() )->get_data()['url'] === $checkout->get_data()['url'], 'Repeated checkout requests reuse an existing open session' );
$calls = get_option( 'rt_mock_stripe_calls' );
check( count( array_filter( $calls, function ( $call ) { return $call['path'] === 'checkout/sessions' && $call['mode'] === 'live'; } ) ) === 1, 'Repeated clicks cannot create multiple payable checkout sessions' );
check( billing_event( $payer, 'live', 'customer.subscription.updated', array(), false )->get_status() === 400 && billing_event( $payer, 'live', 'customer.subscription.updated', array(), true, time() - 600 )->get_status() === 400, 'Webhooks reject missing signatures and expired signed requests' );
check( billing_event( $payer, 'live', 'customer.subscription.updated', array( 'livemode' => false ) )->get_status() === 400, 'Test events cannot grant live membership access' );
check( is_wp_error( RT_Stripe::reconcile_return( $other_payer, 'live', $row['checkout_id'] ) ), 'Another user cannot claim a checkout session from its URL' );
check( is_wp_error( RT_Stripe::reconcile_return( $payer, 'live', $row['checkout_id'] ) ) && call_api( $payer, 'GET', 'entries' )->get_status() === 402, 'An unpaid checkout return does not grant access' );
rt_mock_complete_checkout( $payer );
check( billing_event( $payer )->get_status() === 200 && call_api( $payer, 'GET', 'entries' )->get_data()['items'][0]['title'] === 'My retained paid diary', 'Verified payment opens the original saved diary' );
check( call_api( $other_payer, 'GET', 'entries' )->get_status() === 402, 'One person’s subscription does not cover another account' );
check( call_api( $payer, 'POST', 'billing/checkout', array() )->get_status() === 409, 'An existing subscriber cannot buy a duplicate subscription' );
check( call_api( $payer, 'POST', 'billing/portal', array( 'customer' => 'cus_someoneElse' ) )->get_status() === 200, 'Subscribers can manage billing using their own server-mapped customer' );
$calls = get_option( 'rt_mock_stripe_calls' ); $last = end( $calls );
check( $last['data']['customer'] === $row['customer_id'], 'The portal ignores a client-supplied customer ID' );
rt_mock_subscription( $payer, 'live', array( 'cancel_at_period_end' => true ) ); billing_event( $payer );
check( call_api( $payer, 'GET', 'membership' )->get_data()['state'] === 'ending' && call_api( $payer, 'GET', 'entries' )->get_status() === 200, 'Cancellation retains access through the paid period' );
rt_mock_subscription( $payer, 'live', array( 'status' => 'past_due', 'latest_invoice' => array( 'status' => 'open' ) ) ); billing_event( $payer, 'live', 'invoice.payment_failed' );
check( call_api( $payer, 'GET', 'entries' )->get_status() === 402 && call_api( $payer, 'POST', 'billing/portal', array() )->get_status() === 200, 'A failed renewal closes diary access while leaving payment management available' );
rt_mock_subscription( $payer ); billing_event( $payer, 'live', 'invoice.paid' );
check( call_api( $payer, 'GET', 'entries' )->get_status() === 200, 'A successful renewal restores access' );
rt_mock_subscription( $payer, 'live', array( 'status' => 'canceled' ) ); billing_event( $payer, 'live', 'customer.subscription.deleted' );
check( call_api( $payer, 'GET', 'entries' )->get_status() === 402, 'An ended subscription cannot open the diary' );
billing_event( $payer, 'live', 'invoice.paid' );
check( call_api( $payer, 'GET', 'entries' )->get_status() === 402, 'A delayed or replayed old payment event cannot revive a canceled subscription' );
rt_mock_subscription( $payer, 'live', array( 'items' => array( 'data' => array( array( 'current_period_end' => time() - 1 ) ) ) ) ); billing_event( $payer );
check( call_api( $payer, 'GET', 'entries' )->get_status() === 402, 'Access ends at the paid-through timestamp even before a cancellation event arrives' );
rt_mock_subscription( $payer, 'live', array( 'metadata' => array( 'rt_user' => (string) $other_payer ) ) ); billing_event( $payer );
check( call_api( $payer, 'GET', 'entries' )->get_status() === 402, 'A subscription must match the customer’s WordPress identity' );
check( call_api( $payer, 'POST', 'billing/checkout', array() )->get_status() === 409, 'A misconfigured existing subscription blocks another checkout instead of risking a duplicate charge' );
rt_mock_subscription( $payer, 'live', array( 'items' => array( 'data' => array( array( 'price' => array( 'unit_amount' => 1 ) ) ) ) ) ); billing_event( $payer );
check( call_api( $payer, 'GET', 'entries' )->get_status() === 402, 'An unrelated or incorrectly priced subscription cannot grant app access' );
update_option( 'rt_mock_stripe_failure', true );
check( billing_event( $payer )->get_status() === 503, 'Provider failures return a retryable webhook error rather than acknowledging lost updates' );
delete_option( 'rt_mock_stripe_failure' );
wp_set_current_user( $billing_admin ); ob_start(); RT_Stripe_Settings::render(); $settings_html = ob_get_clean();
check( ! str_contains( $settings_html, 'sk_live_1234567890123456' ) && ! str_contains( $settings_html, 'whsec_Reellive' ), 'Saved Stripe secrets never reappear in settings HTML' );
check( ! str_contains( wp_json_encode( call_api( $payer, 'GET', 'membership' )->get_data() ), 'cus_' ), 'Membership responses expose neither billing identifiers nor keys' );
wp_set_current_user( $billing_admin ); RT_Stripe_Settings::set_enabled( false );
check( call_api( $payer, 'GET', 'entries' )->get_status() === 200 && call_api( $payer, 'POST', 'billing/portal', array() )->get_status() === 200, 'Turning off paid access preserves stored diaries and access to existing subscription management' );
