<?php
$family_author = new_user( 'family_author' ); $family_reader = new_user( 'family_reader' );
$wife = call_api( $family_author, 'POST', 'companions', array( 'name' => 'My wife' ) )->get_data();
$son = call_api( $family_author, 'POST', 'companions', array( 'name' => 'My elder son' ) )->get_data();
check( $wife['id'] > 0 && $son['id'] > 0 && $wife['can_edit'], 'Creates reusable companion labels without creating accounts for them' );
check( call_api( $family_author, 'POST', 'companions', array( 'name' => 'My wife' ) )->get_data()['id'] === $wife['id'], 'Adding the same companion reuses their identity' );
check( call_api( 0, 'POST', 'companions', array( 'name' => 'Anonymous' ) )->get_status() === 401, 'Companion management requires authentication' );
check( call_api( $family_reader, 'GET', 'bootstrap' )->get_data()['companions'] === array(), 'Unused personal companion profiles stay private' );
$body = viewing( 'Companion repeat film' ); $body['watch_company'] = 'companions'; $body['companion_ids'] = array( $wife['id'] );
$wife_viewing = call_api( $family_author, 'POST', 'entries', $body )->get_data()['id'];
$body['companion_ids'] = array( $son['id'] );
call_api( $family_author, 'POST', 'entries', $body );
$body['companion_ids'] = array( $wife['id'], $son['id'] );
$both_viewing = call_api( $family_author, 'POST', 'entries', $body )->get_data()['id'];
$with_wife = call_api( $family_author, 'GET', 'entries', null, array( 'with' => $wife['id'] ) )->get_data();
$with_son = call_api( $family_author, 'GET', 'entries', null, array( 'with' => $son['id'] ) )->get_data();
check( $with_wife['total'] === 2 && $with_son['total'] === 2 && count( $with_wife['items'][0]['companions'] ) === 2, 'Individual companion filters include group viewings without duplicating entries' );
check( $with_wife['items'][0]['movie_id'] === $with_son['items'][1]['movie_id'], 'Rewatches reuse the movie but keep their own participant selections' );
check( call_api( $family_reader, 'GET', 'entries', null, array( 'with' => $wife['id'] ) )->get_data()['total'] === 0, 'Companion filtering never bypasses diary visibility' );
$body['companion_ids'] = array( $wife['id'] );
check( call_api( $family_reader, 'POST', 'entries', $body )->get_status() === 400, 'A viewing cannot claim another author’s companion profile' );
$body['companion_ids'] = array();
check( call_api( $family_author, 'POST', 'entries', $body )->get_status() === 400, 'With-other-people viewings require at least one companion' );
$body['companion_ids'] = array( '1 OR 1=1' );
check( call_api( $family_author, 'POST', 'entries', $body )->get_status() === 400, 'Companion IDs reject malformed values' );
$body['companion_ids'] = array( $wife['id'] ); $body['watch_company'] = 'alone';
check( call_api( $family_author, 'POST', 'entries', $body )->get_status() === 400, 'Alone and companion selections cannot conflict' );
$body['companion_ids'] = array();
call_api( $family_author, 'POST', 'entries', $body );
call_api( $family_author, 'POST', 'entries', viewing( 'Older viewing with unspecified company' ) );
check( call_api( $family_author, 'GET', 'entries', null, array( 'with' => 'alone' ) )->get_data()['total'] === 1 && call_api( $family_author, 'GET', 'entries', null, array( 'with' => 'unspecified' ) )->get_data()['total'] === 1, 'Unspecified older viewings are not misclassified as watched alone' );
check( call_api( $family_author, 'GET', 'entries', null, array( 'with' => array( 1 ) ) )->get_status() === 400, 'Malformed companion filters are rejected' );
check( call_api( $family_reader, 'PUT', 'companions/' . $wife['id'], array( 'name' => 'Changed by someone else' ) )->get_status() === 403, 'Only the profile owner may rename a companion' );
check( call_api( $family_author, 'PUT', 'companions/' . $wife['id'], array( 'name' => 'My elder son' ) )->get_status() === 409, 'Renaming cannot merge two different companions accidentally' );
call_api( $family_author, 'PUT', 'companions/' . $wife['id'], array( 'name' => 'My partner' ) );
$renamed = call_api( $family_author, 'GET', 'entries', null, array( 'with' => $wife['id'] ) )->get_data();
check( $renamed['total'] === 2 && in_array( 'My partner', array_column( $renamed['items'][0]['companions'], 'name' ), true ), 'Renaming a companion updates historical labels while preserving their filter identity' );
call_api( $family_author, 'POST', 'household', array( 'name' => 'Companion test household' ) );
$family_code = call_api( $family_author, 'POST', 'household/invite', array() )->get_data()['code'];
call_api( $family_reader, 'POST', 'household/join', array( 'code' => $family_code ) );
$body = viewing( 'Shared son viewing', 'household' ); $body['watch_company'] = 'companions'; $body['companion_ids'] = array( $son['id'] );
$shared_companion_entry = call_api( $family_author, 'POST', 'entries', $body )->get_data()['id'];
$visible_companions = call_api( $family_reader, 'GET', 'bootstrap' )->get_data()['companions'];
check( count( $visible_companions ) === 1 && $visible_companions[0]['id'] === $son['id'] && ! $visible_companions[0]['can_edit'], 'Household members see only companions referenced by accessible shared viewings' );
check( call_api( $family_reader, 'GET', 'entries', null, array( 'with' => $son['id'] ) )->get_data()['total'] === 1, 'Household members can filter shared viewings by their recorded companions' );
call_api( $family_author, 'DELETE', 'entries/' . $shared_companion_entry );
check( call_api( $family_reader, 'GET', 'bootstrap' )->get_data()['companions'] === array(), 'Removing the last shared viewing removes access to its companion labels' );
$old_edit = viewing( 'Companion repeat film' );
call_api( $family_author, 'PUT', 'entries/' . $wife_viewing, $old_edit );
check( call_api( $family_author, 'GET', 'entries', null, array( 'with' => $wife['id'] ) )->get_data()['total'] === 2, 'Older clients that omit companion fields preserve existing selections on edit' );
$old_edit['watch_company'] = 'alone'; $old_edit['companion_ids'] = array();
call_api( $family_author, 'PUT', 'entries/' . $wife_viewing, $old_edit );
check( call_api( $family_author, 'GET', 'entries', null, array( 'with' => $wife['id'] ) )->get_data()['total'] === 1, 'Editing a viewing updates its companion filter membership' );
