import { readFile, mkdir, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import { startWordPress, projectRoot } from './wordpress.mjs';
import { checkSearchLayout } from './check-search-layout.mjs';
import { checkSharing } from '../tests/sharing-browser.mjs';
import { checkBilling } from '../tests/billing-browser.mjs';

const instance = await startWordPress({ port: 9401 });
let browser;
try {
  await instance.playground.mkdirTree('/wordpress/wp-content/mu-plugins');
  await instance.playground.writeFile('/wordpress/wp-content/mu-plugins/reel-test-kinopoisk.php', await readFile(path.join(projectRoot, 'tests/mock-kinopoisk.php'), 'utf8'));
  await instance.playground.writeFile('/wordpress/wp-content/mu-plugins/reel-test-stripe.php', await readFile(path.join(projectRoot, 'tests/mock-stripe.php'), 'utf8'));
  await instance.playground.writeFile('/wordpress/reel-invitation-checks.php', await readFile(path.join(projectRoot, 'tests/invitations.php'), 'utf8'));
  await instance.playground.writeFile('/wordpress/reel-companion-checks.php', await readFile(path.join(projectRoot, 'tests/companions.php'), 'utf8'));
  await instance.playground.writeFile('/wordpress/reel-sharing-checks.php', await readFile(path.join(projectRoot, 'tests/sharing.php'), 'utf8'));
  await instance.playground.writeFile('/wordpress/reel-billing-checks.php', await readFile(path.join(projectRoot, 'tests/billing.php'), 'utf8'));
  const result = await instance.playground.run({ code: await readFile(path.join(projectRoot, 'tests/integration.php'), 'utf8') });
  if (result.errors) console.error(result.errors);
  const report = JSON.parse(result.text);
  for (const name of report.passed) console.log(`PASS ${name.length > 160 ? name.slice(0, 160) + '…' : name}`);
  assert.equal(report.failure, undefined, `PHP integration failure at line ${report.line}: ${report.failure}`);
  assert.ok(!result.errors, 'PHP did not emit warnings or errors');
  console.log(`\n${report.passed.length} integration checks passed on WordPress ${report.wordpress}, PHP ${report.php}.`);

  const launch = { headless: true };
  if (process.env.REEL_BROWSER_CHANNEL) launch.channel = process.env.REEL_BROWSER_CHANNEL;
  else if (process.platform === 'darwin') launch.channel = 'chrome';
  browser = await chromium.launch(launch);
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const url = instance.serverUrl;
  await page.goto(url);
  await expect(page.getByRole('heading', { name: 'Come on in.' })).toBeVisible();
  await page.getByLabel('Username or Email Address').fill('browser');
  await page.getByLabel('Password', { exact: true }).fill('test-movie-night');
  await page.getByRole('button', { name: 'Open my diary' }).click();
  await expect(page.getByRole('heading', { name: 'Your life in movies.' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Your first memory starts here.' })).toBeVisible();

  // A logged-in cookie without a REST nonce must still be rejected.
  const noNonce = await page.evaluate(async () => {
    const response = await fetch(window.ReelTogether.api + 'bootstrap');
    return response.status;
  });
  assert.equal(noNonce, 401, 'Cookie alone must not grant REST access');
  await page.getByRole('button', { name: '＋ Log a film', exact: true }).click();
  await page.getByLabel('Film title', { exact: true }).fill('The Grand Budapest Hotel');
  await page.getByLabel('Release year').fill('2014');
  await page.getByLabel('Date watched').fill('2025-03-14');
  await page.getByRole('dialog').getByLabel('Your rating').selectOption('5');
  await page.getByLabel('Watched with', { exact: true }).last().selectOption('companions');
  await page.getByLabel('Add someone else', { exact: true }).fill('Alex');
  await page.getByRole('button', { name: 'Add person', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'Alex', exact: true })).toBeChecked();
  await page.getByLabel('A little note').fill('A perfect Friday evening.');
  await page.getByRole('button', { name: 'Save film ↗' }).click();
  await expect(page.getByRole('heading', { name: 'The Grand Budapest Hotel', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText('A perfect Friday evening.')).toBeVisible();
  console.log('PASS Browser: login, log a film, reload, and recover the saved entry');

  await page.getByRole('button', { name: 'Edit entry ↗' }).click();
  await page.getByRole('dialog').getByLabel('Your rating').selectOption('4');
  await page.getByLabel('A little note').fill('A new favorite.');
  await page.getByRole('button', { name: 'Save film ↗' }).click();
  await expect(page.getByText('A new favorite.')).toBeVisible();
  await expect(page.getByLabel('Your rating: 4 out of 5 stars')).toBeVisible();
  console.log('PASS Browser: editing preserves the entry and updates its rating');

  await page.getByRole('button', { name: /Our household/ }).click();
  await page.getByLabel('Household name').fill('The Sunday Cinema');
  await page.getByRole('button', { name: 'Create household ↗' }).click();
  await expect(page.getByRole('heading', { name: 'The Sunday Cinema' })).toBeVisible();
  await page.getByRole('button', { name: 'Create invitation code ↗' }).click();
  await expect(page.getByLabel('Share this code')).toHaveValue(/^[a-f0-9]{32}$/);

  await page.getByRole('button', { name: /Watchlist/ }).click();
  await page.getByRole('button', { name: '＋ Add a film', exact: true }).click();
  await page.getByLabel('Film title', { exact: true }).fill('Paddington 2');
  await page.getByLabel('Release year').fill('2017');
  await page.getByLabel('Who can see this?').selectOption('household');
  await page.getByRole('button', { name: 'Save film ↗' }).click();
  await expect(page.getByRole('heading', { name: 'Paddington 2', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Log a viewing ↗' }).click();
  await page.getByLabel('Watched with', { exact: true }).last().selectOption('companions');
  await page.getByRole('button', { name: '＋ My wife', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'My wife', exact: true })).toBeChecked();
  await page.getByRole('button', { name: '＋ My elder son', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'My elder son', exact: true })).toBeChecked();
  await page.getByRole('button', { name: 'Save film ↗' }).click();
  await expect(page.getByRole('heading', { name: 'Your life in movies.' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Paddington 2', exact: true })).toBeVisible();
  console.log('PASS Browser: household creation, invite generation, watchlist → diary');

  const wifeFilter = await page.locator('#companion-filter option').filter({ hasText: /^With My wife$/ }).getAttribute('value');
  const sonFilter = await page.locator('#companion-filter option').filter({ hasText: /^With My elder son$/ }).getAttribute('value');
  await page.locator('#companion-filter').selectOption(wifeFilter);
  await expect(page.getByRole('article')).toHaveCount(1);
  await expect(page.getByRole('heading', { name: 'Paddington 2', exact: true })).toBeVisible();
  await page.locator('#companion-filter').selectOption(sonFilter);
  await expect(page.getByRole('article')).toHaveCount(1);
  await expect(page.getByRole('heading', { name: 'Paddington 2', exact: true })).toBeVisible();
  await page.getByRole('button', { name: /Watching companions/ }).click();
  const wifeForm = page.locator('.companion-edit').filter({ has: page.locator('input[value="My wife"]') });
  await wifeForm.getByLabel('Companion name').fill('My wife (renamed)');
  await wifeForm.getByRole('button', { name: 'Save companion', exact: true }).click();
  await expect(page.locator('.companion-edit input[value="My wife (renamed)"]')).toBeVisible();
  await page.getByRole('button', { name: /Film diary/ }).click();
  await page.locator('#companion-filter').selectOption(wifeFilter);
  await expect(page.getByRole('article')).toHaveCount(1);
  await expect(page.getByRole('article').getByText(/With .*My wife \(renamed\)/)).toBeVisible();
  await page.locator('#companion-filter').selectOption('all');
  const grand = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'The Grand Budapest Hotel', exact: true }) });
  await grand.getByRole('button', { name: 'Edit entry ↗' }).click();
  await page.getByRole('dialog').getByLabel('Watched with', { exact: true }).selectOption('alone');
  await page.getByRole('button', { name: 'Save film ↗' }).click();
  await page.locator('#companion-filter').selectOption('alone');
  await expect(page.getByRole('article')).toHaveCount(1);
  await expect(grand.getByText('Watched alone', { exact: true })).toBeVisible();
  await page.reload();
  await expect(grand.getByText('Watched alone', { exact: true })).toBeVisible();
  console.log('PASS Browser: wife/son group filters, companion renaming across saved viewings, watched-alone editing and persistence');

  const out = path.join(projectRoot, 'test-results');
  await mkdir(out, { recursive: true });
  await checkSearchLayout(page);
  await expect(page.locator('#toast')).toBeHidden({ timeout: 6000 });
  await page.screenshot({ path: path.join(out, 'desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await checkSearchLayout(page);
  await page.screenshot({ path: path.join(out, 'mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Mobile page must fit the viewport');
  await page.getByRole('button', { name: '＋ Log a film', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: 'Edit entry ↗' }).first().click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Delete entry', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Paddington 2', exact: true })).not.toBeVisible();
  console.log('PASS Browser: mobile layout, accessible dialog dismissal, entry deletion');

  await page.getByRole('button', { name: '＋ Log a film', exact: true }).click();
  await page.getByLabel('Movie catalog', { exact: true }).selectOption('kinopoisk');
  await page.getByLabel('Find a movie', { exact: true }).fill('Матрица');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('button', { name: /Матрица.*Kinopoisk 8.5\/10/ }).click();
  await page.getByRole('dialog').getByLabel('Your rating').selectOption('4');
  await page.getByRole('button', { name: 'Save film ↗' }).click();
  const movieCard = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Матрица', exact: true }) });
  await expect(movieCard.getByRole('link', { name: 'Kinopoisk 8.5/10 ↗' })).toHaveAttribute('href', 'https://www.kinopoisk.ru/film/301/');
  await expect(movieCard.getByLabel('Your rating: 4 out of 5 stars')).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Матрица', exact: true })).toBeVisible();
  await expect(movieCard.getByRole('link', { name: 'Kinopoisk 8.5/10 ↗' })).toBeVisible();
  await page.getByRole('button', { name: '＋ Log a film', exact: true }).click();
  await page.getByLabel('Find a movie', { exact: true }).fill('quota');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await expect(page.getByText(/catalog request limit has been reached/)).toBeVisible();
  await page.getByLabel('Film title', { exact: true }).fill('Ручной ввод');
  await page.getByRole('button', { name: 'Save film ↗' }).click();
  await expect(page.getByRole('heading', { name: 'Ручной ввод', exact: true })).toBeVisible();
  console.log('PASS Browser: Russian catalog search, Kinopoisk rating/link, persistence, manual fallback on quota errors');

  await page.getByRole('button', { name: '＋ Log a film', exact: true }).click();
  await page.getByLabel('Kinopoisk link or ID', { exact: true }).fill('https://www.kinopoisk.ru/film/430/');
  await page.getByRole('button', { name: 'Load Kinopoisk details', exact: true }).click();
  await expect(page.getByLabel('Film title', { exact: true })).toHaveValue('Шрэк');
  await expect(page.getByLabel('IMDb link or ID', { exact: true })).toHaveValue('tt0126029');
  await page.getByRole('button', { name: 'Save film ↗' }).click();
  const shrek = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Шрэк', exact: true }) });
  await expect(shrek.getByRole('link', { name: 'Kinopoisk 8.2/10 ↗' })).toHaveAttribute('href', 'https://www.kinopoisk.ru/film/430/');
  await expect(shrek.getByRole('link', { name: 'IMDb 7.9/10 ↗' })).toHaveAttribute('href', 'https://www.imdb.com/title/tt0126029/');
  await page.reload();
  await shrek.getByRole('button', { name: 'Edit entry ↗' }).click();
  await expect(page.getByLabel('Kinopoisk link or ID', { exact: true })).toHaveValue('430');
  await page.getByLabel('IMDb link or ID', { exact: true }).fill('https://www.imdb.com/title/tt0126029/');
  await page.getByRole('button', { name: 'Load IMDb details', exact: true }).click();
  await expect(page.getByLabel('IMDb link or ID', { exact: true })).toHaveValue('tt0126029');
  await page.getByRole('button', { name: 'Save film ↗' }).click();
  await expect(shrek.getByRole('link', { name: 'IMDb 7.9/10 ↗' })).toBeVisible();
  console.log('PASS Browser: exact Kinopoisk and IMDb URL lookup, cross-linked IDs, both ratings, reload and edit');

  await instance.playground.run({ code: "<?php require '/wordpress/wp-load.php'; delete_option('rt_kinopoisk_token');" });
  await page.reload();
  await page.getByRole('button', { name: '＋ Log a film', exact: true }).click();
  await expect(page.getByLabel('Movie catalog', { exact: true })).toHaveCount(0);
  await page.getByLabel('Kinopoisk link or ID', { exact: true }).fill('430');
  await page.getByRole('button', { name: 'Load Kinopoisk details', exact: true }).click();
  await expect(page.locator('#lookup-result')).toContainText('Connect a movie catalog');
  await page.getByLabel('IMDb link or ID', { exact: true }).fill('https://www.imdb.com/title/tt0126029/?ref_=test');
  await page.getByLabel('Film title', { exact: true }).fill('Shrek — manual links');
  await page.getByRole('button', { name: 'Save film ↗' }).click();
  await page.reload();
  const manualLinks = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Shrek — manual links', exact: true }) });
  await expect(manualLinks.getByRole('link', { name: 'Kinopoisk ↗', exact: true })).toHaveAttribute('href', 'https://www.kinopoisk.ru/film/430/');
  await expect(manualLinks.getByRole('link', { name: 'IMDb ↗', exact: true })).toHaveAttribute('href', 'https://www.imdb.com/title/tt0126029/');
  await manualLinks.getByRole('button', { name: 'Edit entry ↗' }).click();
  await page.getByLabel('A little note').fill('Both links kept.');
  await page.getByRole('button', { name: 'Save film ↗' }).click();
  await expect(manualLinks.getByRole('link', { name: 'IMDb ↗', exact: true })).toBeVisible();
  const favicon = page.locator('link[rel="icon"][type="image/svg+xml"]');
  await expect(favicon).toHaveAttribute('href', /assets\/favicon\.svg\?ver=0\.6\.0/);
  assert.equal((await page.request.get(await favicon.getAttribute('href'))).ok(), true);
  console.log('PASS Browser: both ID links persist and edit without an API key; branded favicon loads');

  const outsider = await browser.newContext();
  const outsiderPage = await outsider.newPage();
  await outsiderPage.goto(url);
  await expect(outsiderPage.getByRole('heading', { name: 'Come on in.' })).toBeVisible();
  await expect(outsiderPage.getByText('A new favorite.')).not.toBeVisible();
  await outsiderPage.locator('#request-invitation summary').click();
  await outsiderPage.getByLabel('Your name', { exact: true }).fill('Browser invitation visitor');
  await outsiderPage.getByLabel('Email address', { exact: true }).fill('browser-invitation@example.test');
  await outsiderPage.getByRole('button', { name: 'Request an invitation', exact: true }).click();
  await expect(outsiderPage.locator('.invitation-message')).toContainText('Your request has been received');
  await expect(outsiderPage).toHaveURL(/invitation=received/);
  await expect(outsiderPage.getByText('browser-invitation@example.test')).toHaveCount(0);
  await outsiderPage.setViewportSize({ width: 390, height: 844 });
  await outsiderPage.goto(url);
  await outsiderPage.locator('#request-invitation summary').click();
  assert.equal(await outsiderPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Invitation form fits on mobile');
  await outsiderPage.screenshot({ path: path.join(out, 'invitation-mobile.png'), fullPage: true });
  await outsider.close();
  const administrator = await browser.newContext();
  const adminPage = await administrator.newPage();
  await adminPage.goto(url);
  await adminPage.getByLabel('Username or Email Address').fill('reviewer');
  await adminPage.getByLabel('Password', { exact: true }).fill('test-movie-night');
  await adminPage.getByRole('button', { name: 'Open my diary' }).click();
  await adminPage.getByRole('link', { name: /Invitation requests/ }).click();
  const requestRow = adminPage.getByRole('row').filter({ hasText: 'browser-invitation@example.test' });
  await expect(requestRow).toBeVisible();
  await requestRow.getByRole('button', { name: 'Mark handled', exact: true }).click();
  await expect(adminPage.getByText('Request updated.', { exact: true })).toBeVisible();
  await expect(adminPage.getByText('browser-invitation@example.test')).toHaveCount(0);
  await adminPage.getByLabel('Show requests').selectOption('handled');
  await adminPage.getByRole('button', { name: 'Filter', exact: true }).click();
  await expect(requestRow.getByText('Handled', { exact: true })).toBeVisible();
  const accountCheck = await instance.playground.run({ code: "<?php require '/wordpress/wp-load.php'; echo email_exists('browser-invitation@example.test') ? 'created' : 'absent';" });
  assert.equal(accountCheck.text, 'absent', 'Handling a request does not create an account');
  await requestRow.getByRole('button', { name: 'Delete request', exact: true }).click();
  await expect(adminPage.getByText('browser-invitation@example.test')).toHaveCount(0);
  await administrator.close();
  console.log('PASS Browser: public invitation request, mobile form, administrator queue, manual handling and deletion without account creation');
  assert.deepEqual(errors, [], 'No browser JavaScript errors');
  console.log('PASS Browser: logged-out sessions cannot see diary content; no JavaScript errors');
  await checkSharing(browser, url, out);
  await checkBilling(browser, instance, out);

  const storage = await mkdtemp(path.join(tmpdir(), 'reel-persistence-'));
  let persistent;
  try {
    persistent = await startWordPress({ port: 9402, storage, setup: `
      $uid = wp_create_user('persist', 'local-test-password');
      wp_set_current_user($uid);
      $req = new WP_REST_Request('POST', '/reel-together/v1/entries');
      $req->set_header('Content-Type', 'application/json');
      $req->set_body(wp_json_encode(array('movie'=>array('title'=>'A lasting memory','year'=>2020), 'status'=>'watched', 'scope'=>'personal', 'watched_on'=>'2025-01-01')));
      $saved = rest_do_request($req);
      if ($saved->get_status() !== 201) { throw new Exception('Persistence fixture failed'); }
    ` });
    await persistent[Symbol.asyncDispose]();
    persistent = undefined;
    persistent = await startWordPress({ port: 9402, storage });
    const persisted = await persistent.playground.run({ code: `<?php
      require '/wordpress/wp-load.php';
      wp_set_current_user(get_user_by('login', 'persist')->ID);
      $response = rest_do_request(new WP_REST_Request('GET', '/reel-together/v1/entries'));
      echo wp_json_encode($response->get_data());
    ` });
    assert.equal(JSON.parse(persisted.text).items[0].title, 'A lasting memory');
    console.log('PASS Persistence: saved diary survives stopping and restarting WordPress');
  } finally {
    if (persistent) await persistent[Symbol.asyncDispose]();
    await rm(storage, { recursive: true, force: true });
  }
  console.log('\nAll tests passed. Screenshots: test-results/desktop.png and mobile.png.');
} finally {
  if (browser) await browser.close();
  await instance[Symbol.asyncDispose]();
}
